/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 office_desk.glb 
Author: snaptoongames (https://sketchfab.com/snaptoongames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-desk-e0f8dc2f81d440a09e9519fdc9e74cb2
Title: Office Desk
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Desk(props) {
  const { nodes, materials } = useGLTF('/models/office_desk.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.102}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[43.729, 0.4, -8.044]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0_MI_Color_M06_1_0.geometry} material={materials.MI_Color_M06_1} />
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0_MI_Color_M03_0.geometry} material={materials.MI_Color_M03} />
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0_MI_Color_M05_1_0.geometry} material={materials.MI_Color_M05_1} />
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0_MI_Object_78_0.geometry} material={materials.MI_Object_78} />
          </group>
          <group position={[-4.233, 0.4, -30.381]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.deskoffice1228A6_StaticMeshComponent0_MI_Object_73_0.geometry} material={materials.MI_Object_73} />
            <mesh geometry={nodes.deskoffice1228A6_StaticMeshComponent0_MI_Color_C06_0.geometry} material={materials.MI_Color_C06} />
            <mesh geometry={nodes.deskoffice1228A6_StaticMeshComponent0_MI_Object_51_0.geometry} material={materials.MI_Object_51} />
            <mesh geometry={nodes.deskoffice1228A6_StaticMeshComponent0_MI_Object_62_1_0.geometry} material={materials.MI_Object_62_1} />
          </group>
          <group position={[-5.533, 0.4, 60.133]} rotation={[-Math.PI / 2, 0, -1.571]} scale={100}>
            <mesh geometry={nodes.drawer1228C6_StaticMeshComponent0_MI_Default_0.geometry} material={materials.MI_Default} />
            <mesh geometry={nodes.drawer1228C6_StaticMeshComponent0_MI_Color_I05_1_0.geometry} material={materials.MI_Color_I05_1} />
            <mesh geometry={nodes.drawer1228C6_StaticMeshComponent0_MI_Color_A01_3_0.geometry} material={materials.MI_Color_A01_3} />
          </group>
          <group position={[12.987, 78.4, 12.228]} rotation={[-Math.PI / 2, 0, -2.007]} scale={100}>
            <mesh geometry={nodes.monitor1228A6_StaticMeshComponent0_MI_plasticwhite03_0.geometry} material={materials.MI_plasticwhite03} />
            <mesh geometry={nodes.monitor1228A6_StaticMeshComponent0_MI_Object_67_0.geometry} material={materials.MI_Object_67} />
            <mesh geometry={nodes.monitor1228A6_StaticMeshComponent0_MI_Object_74_0.geometry} material={materials.MI_Object_74} />
          </group>
          <group position={[27.691, 78.4, -31.287]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_paper01_0.geometry} material={materials.MI_paper01} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Color_A05_0.geometry} material={materials.MI_Color_A05} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Metal_Aluminum_Anodized_0.geometry} material={materials.MI_Metal_Aluminum_Anodized} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Color_F06_0.geometry} material={materials.MI_Color_F06} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Chrome1_0.geometry} material={materials.MI_Chrome1} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Object_0137_Black__0.geometry} material={materials.MI_Object_0137_Black} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Color_B04_1_0.geometry} material={materials.MI_Color_B04_1} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Color_M05_0.geometry} material={materials.MI_Color_M05} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Color_M04_0.geometry} material={materials.MI_Color_M04} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Color_G05_0.geometry} material={materials.MI_Color_G05} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Object_66_0.geometry} material={materials.MI_Object_66} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_W1_0.geometry} material={materials.MI_W1} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Color_D01_0.geometry} material={materials.MI_Color_D01} />
            <mesh geometry={nodes.documents1228H12_StaticMeshComponent0_MI_Color_008_0.geometry} material={materials.MI_Color_008} />
          </group>
          <group position={[26.251, 96.2, -75.066]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.documents1228J2_StaticMeshComponent0_MI_Default_2_0.geometry} material={materials.MI_Default_2} />
            <mesh geometry={nodes.documents1228J2_StaticMeshComponent0_MI_Color_F06_1_0.geometry} material={materials.MI_Color_F06_1} />
            <mesh geometry={nodes.documents1228J2_StaticMeshComponent0_MI_Color_G05_1_0.geometry} material={materials.MI_Color_G05_1} />
            <mesh geometry={nodes.documents1228J2_StaticMeshComponent0_MI_Color_B04_1_1_0.geometry} material={materials.MI_Color_B04_1_1} />
            <mesh geometry={nodes.documents1228J2_StaticMeshComponent0_MI_Color_M04_1_0.geometry} material={materials.MI_Color_M04_1} />
            <mesh geometry={nodes.documents1228J2_StaticMeshComponent0_MI_Object_131_0.geometry} material={materials.MI_Object_131} />
            <mesh geometry={nodes.documents1228J2_StaticMeshComponent0_MI_W1_1_0.geometry} material={materials.MI_W1_1} />
          </group>
          <group position={[6.918, 0.4, 17.955]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.desktop1228A3_StaticMeshComponent0_MI_Color_L25_0.geometry} material={materials.MI_Color_L25} />
            <mesh geometry={nodes.desktop1228A3_StaticMeshComponent0_MI_Color_A05_2_0.geometry} material={materials.MI_Color_A05_2} />
            <mesh geometry={nodes.desktop1228A3_StaticMeshComponent0_MI_Color_B01_0.geometry} material={materials.MI_Color_B01} />
          </group>
          <group position={[-23.9, 78.4, -40.323]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Ballpen1228A4_StaticMeshComponent0_MI_Object_103_0.geometry} material={materials.MI_Object_103} />
            <mesh geometry={nodes.Ballpen1228A4_StaticMeshComponent0_MI_Metal_Corrogated_Shiny_0.geometry} material={materials.MI_Metal_Corrogated_Shiny} />
          </group>
          <group position={[-2.941, 78.4, -83.36]} rotation={[-Math.PI / 2, 0, -0.873]} scale={100}>
            <mesh geometry={nodes.telephone1228A6_StaticMeshComponent0_MI_plasticwhite03_0.geometry} material={materials.MI_plasticwhite03} />
            <mesh geometry={nodes.telephone1228A6_StaticMeshComponent0_MI_Color_M07_0.geometry} material={materials.MI_Color_M07} />
          </group>
          <group position={[-57.067, 0.4, -24.957]} rotation={[-Math.PI / 2, 0, 1.484]} scale={100}>
            <mesh geometry={nodes.Officechair1228C6_StaticMeshComponent0_MI_Color_M08_0.geometry} material={materials.MI_Color_M08} />
            <mesh geometry={nodes.Officechair1228C6_StaticMeshComponent0_MI_plasticGrey_0.geometry} material={materials.MI_plasticGrey} />
          </group>
          <group position={[12.556, 70.467, 65.518]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100}>
            <mesh geometry={nodes.documents1228F_455_StaticMeshComponent0_MI_Object_41_0.geometry} material={materials.MI_Object_41} />
            <mesh geometry={nodes.documents1228F_455_StaticMeshComponent0_MI_Default_0.geometry} material={materials.MI_Default} />
          </group>
          <group position={[-27.603, 70.467, 71.732]} rotation={[-Math.PI / 2, 0, -1.571]} scale={100}>
            <mesh geometry={nodes.documents1228J4_458_StaticMeshComponent0_MI_Default_2_0.geometry} material={materials.MI_Default_2} />
            <mesh geometry={nodes.documents1228J4_458_StaticMeshComponent0_MI_Color_F06_1_0.geometry} material={materials.MI_Color_F06_1} />
            <mesh geometry={nodes.documents1228J4_458_StaticMeshComponent0_MI_Color_G05_1_0.geometry} material={materials.MI_Color_G05_1} />
            <mesh geometry={nodes.documents1228J4_458_StaticMeshComponent0_MI_Color_B04_1_1_0.geometry} material={materials.MI_Color_B04_1_1} />
            <mesh geometry={nodes.documents1228J4_458_StaticMeshComponent0_MI_Color_M04_1_0.geometry} material={materials.MI_Color_M04_1} />
            <mesh geometry={nodes.documents1228J4_458_StaticMeshComponent0_MI_Object_131_0.geometry} material={materials.MI_Object_131} />
            <mesh geometry={nodes.documents1228J4_458_StaticMeshComponent0_MI_W1_1_0.geometry} material={materials.MI_W1_1} />
          </group>
          <group position={[-8.034, 0.4, -104.411]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0001_MI_Color_M06_1_0.geometry} material={materials.MI_Color_M06_1} />
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0001_MI_Color_M03_0.geometry} material={materials.MI_Color_M03} />
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0001_MI_Color_M05_1_0.geometry} material={materials.MI_Color_M05_1} />
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0001_MI_Object_78_0.geometry} material={materials.MI_Object_78} />
          </group>
          <group position={[-20.709, 110.425, -102.438]} scale={100}>
            <mesh geometry={nodes.Notepaper1228D10_StaticMeshComponent0001_MI_paper01_0.geometry} material={materials.MI_paper01} />
            <mesh geometry={nodes.Notepaper1228D10_StaticMeshComponent0001_MI_Object_13_0.geometry} material={materials.MI_Object_13} />
          </group>
          <group position={[-8.034, 0.4, 89.59]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0002_MI_Color_M06_1_0.geometry} material={materials.MI_Color_M06_1} />
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0002_MI_Color_M03_0.geometry} material={materials.MI_Color_M03} />
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0002_MI_Color_M05_1_0.geometry} material={materials.MI_Color_M05_1} />
            <mesh geometry={nodes.partition1228A4_StaticMeshComponent0002_MI_Object_78_0.geometry} material={materials.MI_Object_78} />
          </group>
          <mesh geometry={nodes.keyboard1228A6_StaticMeshComponent0_MI_keyboadcolor_0.geometry} material={materials.MI_keyboadcolor} position={[-13.042, 78.4, -17.846]} rotation={[-Math.PI / 2, 0, -2.269]} scale={100} />
          <mesh geometry={nodes.paper1228A5_StaticMeshComponent0_MI_paper001_0.geometry} material={materials.MI_paper001} position={[-21.547, 78.4, -57.549]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.drawer1228D16_StaticMeshComponent0_MI_plasticwhite03_0.geometry} material={materials.MI_plasticwhite03} position={[20.067, 78.4, -89.897]} rotation={[-Math.PI / 2, 0, -1.571]} scale={100} />
          <mesh geometry={nodes.drawer1228D17_StaticMeshComponent0_MI_plasticwhite03_0.geometry} material={materials.MI_plasticwhite03} position={[20.067, 78.4, -75.521]} rotation={[-Math.PI / 2, 0, -1.571]} scale={100} />
          <mesh geometry={nodes.drawer1228D18_StaticMeshComponent0_MI_plasticwhite03_0.geometry} material={materials.MI_plasticwhite03} position={[20.067, 78.4, -60.987]} rotation={[-Math.PI / 2, 0, -1.571]} scale={100} />
          <mesh geometry={nodes.Notepaper122bA2_StaticMeshComponent0_MI_0046_Gold_0.geometry} material={materials.MI_0046_Gold} position={[-41.76, 102.238, -102.438]} scale={100} />
          <mesh geometry={nodes.Notepaper1228D10_StaticMeshComponent0_MI_paper01_0.geometry} material={materials.MI_paper01} position={[-20.709, 110.425, -102.438]} scale={100} />
          <mesh geometry={nodes.cup1228A6_StaticMeshComponent0_MI_plasticwhite03_0.geometry} material={materials.MI_plasticwhite03} position={[-30.602, 78.4, -83.538]} rotation={[-Math.PI / 2, 0, 0]} scale={68.523} />
          <mesh geometry={nodes.tissue1228A2_StaticMeshComponent0_MI_white_0.geometry} material={materials.MI_white} position={[-1.152, 78.4, -63.953]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Notepaper1228D11_StaticMeshComponent0_MI_paper01_0.geometry} material={materials.MI_paper01} position={[41.815, 108.535, 33.465]} rotation={[0, -1.571, 0]} scale={100} />
          <mesh geometry={nodes.Notepaper1228D12_StaticMeshComponent0_MI_paper01_0.geometry} material={materials.MI_paper01} position={[41.815, 108.535, 54.51]} rotation={[0, -1.571, 0]} scale={100} />
          <mesh geometry={nodes.Notepaper1228D13_StaticMeshComponent0_MI_paper01_0.geometry} material={materials.MI_paper01} position={[41.815, 108.535, 75.306]} rotation={[0, -1.571, 0]} scale={100} />
          <mesh geometry={nodes.Notepaper1228D14_StaticMeshComponent0_MI_paper01_0.geometry} material={materials.MI_paper01} position={[22.012, 107.548, 87.578]} rotation={[-Math.PI, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes.Notepaper1228D15_StaticMeshComponent0_MI_paper01_0.geometry} material={materials.MI_paper01} position={[0.658, 107.548, 87.578]} rotation={[-Math.PI, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes.Notepaper1228D16_StaticMeshComponent0_MI_paper01_0.geometry} material={materials.MI_paper01} position={[-23.001, 107.548, 87.578]} rotation={[-Math.PI, 0, -Math.PI]} scale={115.506} />
          <mesh geometry={nodes.mouse1228A10_StaticMeshComponent0_MI_plasticwhite03_0.geometry} material={materials.MI_plasticwhite03} position={[-17.38, 78.4, 23.371]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.Notepaper1228B8_464_StaticMeshComponent0_MI_0046_Gold_0.geometry} material={materials.MI_0046_Gold} position={[2.221, 83.795, 17.585]} rotation={[-2.747, -1.114, -1.224]} scale={100} />
          <mesh geometry={nodes.Notepaper1228B9_StaticMeshComponent0_MI_0046_Gold_0.geometry} material={materials.MI_0046_Gold} position={[6.689, 83.906, 7.784]} rotation={[-2.747, -1.114, -1.224]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/office_desk.glb')
